import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import CosyLogo from "./cosy-corner-logo.jpg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="flex justify-center p-5">
        <Image
          src={CosyLogo}
          className="-mt-20"
          alt="Cosy Songs Logo"
          width={400}
          height={400}
          priority={true}
        />
        {children}
      </body>
    </html>
  );
}
