import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="flex justify-center items-center flex-col px-5 py-10">
        <h1
          className="uppercase text-7xl font-workbench mb-10"
          style={{
            transform: "skew(-0.03turn, -3deg)",
            backgroundImage:
              "linear-gradient(to right, #ffffff, #fd9c9c, #ffffff)",
            backgroundClip: "text",
            color: "transparent",
            animation: "move-background 4s linear infinite",
          }}
        >
          Cosy songs
        </h1>
        {children}
      </body>
    </html>
  );
}
